out_dir: results/degre_mult
metric_best: accuracy
wandb:
  use: True
  project: LRGB-Benchmark-RandomSeed
  entity: vjd5zr
dataset:
  format: HCP
  name: HCPGender
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  split_mode: random
  split: [0.5, 0.2, 0.3]
train:
  mode: custom
  batch_size: 128 
  eval_period: 1
  ckpt_period: 60
  ckpt_period: 60
  enable_ckpt: False
  # auto_resume: True
  # epoch_resume: 59
model:
  type: custom_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
  graph_index: True
  gnn_explainer: False
gnn:
  # head: inductive_node
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 3
  dim_inner: 108
  layer_type: gcn
  act: relu
  residual: True
  dropout: 0.0
  agg: sum
  normalize_adj: False
optim:
  optimizer: adam
  weight_decay: 1e-5
  base_lr: 1e-4
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
